// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/books.proto

package books

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Books service

func NewBooksEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Books service

type BooksService interface {
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type booksService struct {
	c    client.Client
	name string
}

func NewBooksService(name string, c client.Client) BooksService {
	return &booksService{
		c:    c,
		name: name,
	}
}

func (c *booksService) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Books.List", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksService) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Books.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Books service

type BooksHandler interface {
	List(context.Context, *ListRequest, *Response) error
	Get(context.Context, *Request, *Response) error
}

func RegisterBooksHandler(s server.Server, hdlr BooksHandler, opts ...server.HandlerOption) error {
	type books interface {
		List(ctx context.Context, in *ListRequest, out *Response) error
		Get(ctx context.Context, in *Request, out *Response) error
	}
	type Books struct {
		books
	}
	h := &booksHandler{hdlr}
	return s.Handle(s.NewHandler(&Books{h}, opts...))
}

type booksHandler struct {
	BooksHandler
}

func (h *booksHandler) List(ctx context.Context, in *ListRequest, out *Response) error {
	return h.BooksHandler.List(ctx, in, out)
}

func (h *booksHandler) Get(ctx context.Context, in *Request, out *Response) error {
	return h.BooksHandler.Get(ctx, in, out)
}
